// Generated by CoffeeScript 1.12.1
(function() {
  var $backToTechnician, $event, $markAsUnavailable, $multiFilter, $removeUnavailablity, $scheduler, areasValues, filterable, layouts, loadEvents, loadResources, manualViewRender, momentToApex, optionsValues, param, pls, search, selected, serviceValues, setNowBackground, v,
    indexOf = [].indexOf || function(item) { for (var i = 0, l = this.length; i < l; i++) { if (i in this && this[i] === item) return i; } return -1; };

  search = decodeURIComponent(location.search);

  param = {
    availability: search.indexOf('?availability') !== -1 || search.indexOf('&availability') !== -1,
    technicians: (search.split('?technicians=')[1] || search.split('&technicians=')[1] || '').split('&')[0],
    assignment: search.indexOf('?assignment') !== -1 || search.indexOf('&assignment') !== -1,
    areas: (search.split('?areas=')[1] || search.split('&areas=')[1] || '').split('&')[0],
    services: (search.split('?services=')[1] || search.split('&services=')[1] || '').split('&')[0],
    options: (search.split('?options=')[1] || search.split('&options=')[1] || '').split('&')[0]
  };

  momentToApex = function(obj) {
    return obj.toJSON().split('.')[0].replace('T', ' ');
  };

  if (!param.availability) {
    filterable = true;
    manualViewRender = false;
  }

  loadResources = function(cb) {
    return $.ajax({
      url: url + "?loadResources",
      xhrFields: {
        withCredentials: true
      },
      success: function(data) {
        cb(_.chain(data).filter(function(obj) {
          var id, ref, ref1, selects, services, v;
          if (filterable) {
            selects = $multiFilter.multipleSelect('getSelects');
            services = obj.Service_Type__c ? (function() {
              var j, len, ref, results;
              ref = obj.Service_Type__c.split(';');
              results = [];
              for (j = 0, len = ref.length; j < len; j++) {
                v = ref[j];
                results.push("s:" + v);
              }
              return results;
            })() : [];
            return (ref = "a:" + obj.Area__c, indexOf.call(selects, ref) >= 0) && _.intersection(services, selects).length && (indexOf.call(selects, "o:Availability") >= 0 ? !obj.Calendar_Items__r : true);
          }
          return ref1 = obj.Id.slice(0, 15), indexOf.call((function() {
            var j, len, ref2, results;
            ref2 = param.technicians.split(';');
            results = [];
            for (j = 0, len = ref2.length; j < len; j++) {
              id = ref2[j];
              results.push(id.slice(0, 15));
            }
            return results;
          })(), ref1) >= 0;
        }).map(function(obj) {
          return {
            id: obj.Id,
            title: obj.Name,
            area: obj.Area__c,
            user: obj.User__c,
            dailyNote: obj.Daily_Note__c || ''
          };
        }).sortBy('area').value());
        if (filterable) {
          if (manualViewRender) {
            $scheduler.fullCalendar('option', 'viewRender').call($scheduler.fullCalendar('getView'));
          }
          return manualViewRender = true;
        }
      }
    });
  };

  loadEvents = function(start, end, timezone, cb) {
    return $.ajax({
      url: url + "?loadEvents&start=" + (start.toJSON()) + "&end=" + (end.toJSON()),
      xhrFields: {
        withCredentials: true
      },
      success: function(data) {
        return cb(_.map(data, function(obj) {
          return {
            id: obj.Id,
            title: obj.Work_Order__r ? obj.Work_Order__r.Name + " - " + obj.Name + ", Status: " + obj.Status__c : 'Unavailable',
            status: !obj.Work_Order__r ? 'Unavailable' : obj.Status__c,
            start: obj.Start_Date_and_Time__c,
            end: obj.End_Date_and_Time__c,
            resourceId: obj.Technician__c,
            color: (function() {
              if (!obj.Work_Order__r) {
                return 'red';
              } else {
                switch (obj.Status__c) {
                  case 'Assigned':
                    return 'green';
                  case 'Appointment':
                    return 'yellow';
                  case 'Decline':
                    return 'gray';
                  case 'Confirmed':
                    return 'lightblue';
                  case 'En Route':
                    return 'orange';
                  case 'Loaded':
                    return 'purple';
                  case 'Finished':
                    return 'blue';
                  case 'Canceled':
                    return 'black';
                  default:
                    return 'slategray';
                }
              }
            })()
          };
        }));
      }
    });
  };

  setNowBackground = function() {
    var mm, now;
    now = moment();
    mm = Number(now.format('mm'));
    mm = mm < 30 ? '00' : '30';
    now = (now.format('HH')) + ":" + mm + ":00";
    $('.now-background').removeClass('now-background');
    return $("tr[data-time='" + now + "']").addClass('now-background');
  };

  setInterval(setNowBackground, 1000 * 10);

  setInterval((function() {
    $scheduler.fullCalendar('refetchResources');
    return $scheduler.fullCalendar('refetchEvents');
  }), 1000 * 60);

  $scheduler = $('#scheduler').fullCalendar({
    defaultView: param.availability ? 'agendaWholeWeek' : 'agendaDay',
    timezone: 'local',
    allDaySlot: false,
    handleWindowResize: false,
    height: 'parent',
    header: {
      left: 'prev,next today',
      center: 'title',
      right: 'agendaDay,agendaTwoDays,agendaThreeDays'
    },
    resources: loadResources,
    events: loadEvents,
    views: {
      agendaTwoDays: {
        type: 'agenda',
        duration: {
          days: 2
        },
        groupByResource: true
      },
      agendaThreeDays: {
        type: 'agenda',
        duration: {
          days: 3
        },
        groupByResource: true
      },
      agendaWholeWeek: {
        type: 'agenda',
        duration: {
          days: 7
        },
        groupByResource: true
      }
    },
    viewRender: function() {
      var $areas, $daily, $thead, area, count, dailyNote, days, i, j, k, len, len1, ref, ref1, ref2, resources, tech;
      setNowBackground();
      days = {
        agendaDay: 1,
        agendaTwoDays: 2,
        agendaThreeDays: 3,
        agendaWholeWeek: 7
      }[this.type];
      resources = $scheduler.fullCalendar('getResources');
      $thead = $scheduler.find('.fc-row.fc-widget-header thead');
      i = 0;
      ref = $thead.find('th:not(:first)');
      for (j = 0, len = ref.length; j < len; j++) {
        tech = ref[j];
        if (resources[i++].user) {
          $(tech).append('<u>(U)</u>');
        }
      }
      $areas = $thead.find('tr:first').clone();
      $areas.find('th:not(:first)').remove();
      ref1 = _.countBy(resources, 'area');
      for (area in ref1) {
        count = ref1[area];
        $areas.append("<th class='fc-resource-cell' colspan='" + (days * count) + "'>" + area + "</th>");
      }
      $daily = $thead.find('tr:first').clone();
      $daily.find('th:not(:first)').remove();
      ref2 = _.pluck(resources, 'dailyNote');
      for (k = 0, len1 = ref2.length; k < len1; k++) {
        dailyNote = ref2[k];
        $daily.append("<th class='fc-resource-cell'>" + dailyNote + "</th>");
      }
      $thead.prepend($areas);
      return $thead.append($daily);
    },
    eventClick: param.availability ? function(event, jsEvent, view) {
      if (event.status !== 'Unavailable') {
        return;
      }
      $event.splice(0)[0].css('opacity', '');
      $event.push($(this));
      $event[0].css('opacity', '0.75').data('id', event.id);
      $removeUnavailablity.removeClass('fc-state-disabled').attr('disabled', false);
      return $markAsUnavailable.addClass('fc-state-disabled').attr('disabled', true);
    } : void 0,
    selectable: param.assignment || param.availability,
    select: function(start, end, jsEvent, view, resource) {
      if (param.assignment) {
        return parent.postMessage([momentToApex(start), momentToApex(end), resource.id], '*');
      } else {
        $event.splice(0)[0].css('opacity', '');
        $event.push($());
        $removeUnavailablity.addClass('fc-state-disabled').attr('disabled', true);
        selected.splice(0);
        selected.push(momentToApex(start), momentToApex(end), resource.id);
        return $markAsUnavailable.removeClass('fc-state-disabled').attr('disabled', false);
      }
    }
  });

  if (filterable) {
    layouts = sforce.connection.describeLayout('Technician__c');
    pls = _.find(layouts.recordTypeMappings, (function(rtm) {
      return rtm.defaultRecordTypeMapping;
    })).picklistsForRecordType;
    areasValues = _.sortBy(_.map(_.find(pls, (function(pls) {
      return pls.picklistName === 'Area__c';
    })).picklistValues, (function(plv) {
      return plv.value;
    })));
    serviceValues = _.sortBy(_.map(_.find(pls, (function(pls) {
      return pls.picklistName === 'Service_Type__c';
    })).picklistValues, (function(plv) {
      return plv.value;
    })));
    optionsValues = 'Availability'.split(',');
    $multiFilter = $('<select multiple="multiple"><optgroup label="Area:">{areas}</optgroup><optgroup label="Service Type:">{service}</optgroup><optgroup label="More Options:">{options}</optgroup></select>'.replace('{areas}', ((function() {
      var j, len, results;
      results = [];
      for (j = 0, len = areasValues.length; j < len; j++) {
        v = areasValues[j];
        results.push("<option value='a:" + v + "' " + (!param.areas ? 'selected' : indexOf.call(param.areas.split(';'), v) >= 0 ? 'selected' : '') + ">" + v + "</option>");
      }
      return results;
    })()).join('')).replace('{service}', ((function() {
      var j, len, results;
      results = [];
      for (j = 0, len = serviceValues.length; j < len; j++) {
        v = serviceValues[j];
        results.push("<option value='s:" + v + "' " + (!param.services ? 'selected' : indexOf.call(param.services.split(';'), v) >= 0 ? 'selected' : '') + ">" + v + "</option>");
      }
      return results;
    })()).join('')).replace('{options}', ((function() {
      var j, len, results;
      results = [];
      for (j = 0, len = optionsValues.length; j < len; j++) {
        v = optionsValues[j];
        results.push("<option value='o:" + v + "' " + (!param.options ? 'selected' : indexOf.call(param.options.split(';'), v) >= 0 ? 'selected' : '') + ">" + v + "</option>");
      }
      return results;
    })()).join('')));
    $scheduler.find('.fc-right').prepend($multiFilter);
    $multiFilter.multipleSelect({
      onClose: (function() {
        return $scheduler.fullCalendar('refetchResources');
      })
    });
    $('.ms-parent').find('input[type="checkbox"][data-name="selectGroup"]').remove();
  }

  if (param.availability) {
    $event = [$()];
    selected = [];
    $scheduler.find('.fc-right .fc-button-group').remove();
    $backToTechnician = $('<button>Back To Technician</button>').addClass('fc-button fc-state-default fc-corner-left fc-corner-right').click(function() {
      return open("/" + ($scheduler.fullCalendar('getResources')[0].id), '_parent');
    });
    $removeUnavailablity = $('<button>Remove Unavailablity</button>').addClass('fc-button fc-state-default fc-corner-left fc-corner-right fc-state-disabled').attr('disabled', true).click(function() {
      $removeUnavailablity.addClass('fc-state-disabled').attr('disabled', true);
      sforce.apex.executeAnonymous("Calendar_Item__c event = new Calendar_Item__c(Id='" + ($event[0].data('id')) + "');\ndelete event;");
      return $scheduler.fullCalendar('refetchEvents');
    });
    $markAsUnavailable = $('<button>Mark as Unavailable</button>').addClass('fc-button fc-state-default fc-corner-left fc-corner-right fc-state-disabled').attr('disabled', true).click(function() {
      $markAsUnavailable.addClass('fc-state-disabled').attr('disabled', true);
      sforce.apex.executeAnonymous("Calendar_Item__c event = new Calendar_Item__c();\nevent.Start_Date_and_Time__c = Datetime.valueOfGmt('" + selected[0] + "');\nevent.End_Date_and_Time__c = Datetime.valueOfGmt('" + selected[1] + "');\nevent.Technician__c = '" + selected[2] + "';\ninsert event;");
      return $scheduler.fullCalendar('refetchEvents');
    });
    $scheduler.find('.fc-right').append($markAsUnavailable).append($removeUnavailablity).append($backToTechnician);
  }

  $(window).resize(function() {
    return $scheduler.fullCalendar('option', 'height', this.innerHeight);
  }).resize();

}).call(this);
